# Deploy JS game to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Grant execute permission for gradlew
        working-directory: ./app
        run: chmod +x gradlew
      
      - name: Build JS bundle
        working-directory: ./app
        run: |
          ./gradlew jsBrowserProductionWebpack
      
#      - name: Deploy 🚀 to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@3.7.1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BRANCH: gh-pages
#          FOLDER: app/build/distributions # The folder the action should deploy.
#          # CLEAN: true # Automatically remove deleted files from the deploy branch

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/build/distributions
          destination_dir: app
