# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build API Docs

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: app/**
  pull_request:
    branches: [ "master" ]
    paths: app/**

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Make gradlew executable
      working-directory: ./app
      run: chmod +x ./gradlew

    - name: Build with Gradle
      working-directory: ./app
      run: ./gradlew dokkaHtml
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.9.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: app/build/dokka/html
        destination_dir: api
        

