
name: Tests (with Reports)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: app/**
  pull_request:
    branches: [ "master" ]
    paths: app/**

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Make gradlew executable
      working-directory: ./app
      run: chmod +x ./gradlew

    - name: Build with Gradle
      working-directory: ./app
      run: ./gradlew koverHtmlReport
    
    - name: Deploy Coverage (kover) to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.9.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: app/build/reports/kover/html
        destination_dir: coverage
    
    - name: Deploy Tests to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.9.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: app/build/reports/tests/jvmTestFix/
        # publish_dir: app/build/reports/tests/jvmTest/
        destination_dir: tests

    # Todo - Fix
    # - name: Test Report
    #   uses: dorny/test-reporter@v1
    #   if: success() || failure()                    # run this step even if previous step failed
    #   with:
    #     name: JUnit Tests                           # Name of the check run which will be created
    #     path: app/build/test-results/jvmTest/*.xml  # Path to test results
    #     reporter: java-junit                        # Format of test results

    # - name: Publish Test Results
    #   uses: EnricoMi/publish-unit-test-result-action@v2
    #   if: always()
    #   with:
    #     junit_files: "app/build/test-results/jvmTest/*.xml"
